const icons={home:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V10Z"/><path d="M9 21v-7h6v7"/></svg>',calendar:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>',scan:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 8V5a1 1 0 0 1 1-1h3M16 4h3a1 1 0 0 1 1 1v3M20 16v3a1 1 0 0 1-1 1h-3M8 20H5a1 1 0 0 1-1-1v-3"/><path d="M8 12h8"/></svg>',gift:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="8" width="18" height="13" rx="2"/><path d="M12 8v13M3 12h18M12 8H8.5a2.5 2.5 0 1 1 2.5-2.5V8Zm0 0h3.5A2.5 2.5 0 1 0 13 5.5V8Z"/></svg>',user:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',map:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3-6-3Z"/><path d="M9 3v15M15 6v15"/></svg>',alert:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10.3 3.8 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.8a2 2 0 0 0-3.4 0Z"/><path d="M12 9v4M12 17h.01"/></svg>',box:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m3 7 9-4 9 4-9 4-9-4Z"/><path d="M3 7v10l9 4 9-4V7M12 11v10"/></svg>',chevron:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m9 18 6-6-6-6"/></svg>',settings:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.8 1.8 0 0 0 .36 2l.06.06-2.12 2.12-.06-.06a1.8 1.8 0 0 0-2-.36 1.8 1.8 0 0 0-1.1 1.65v.09h-3v-.09a1.8 1.8 0 0 0-1.1-1.65 1.8 1.8 0 0 0-2 .36l-.06.06-2.12-2.12.06-.06a1.8 1.8 0 0 0 .36-2 1.8 1.8 0 0 0-1.65-1.1H5v-3h.09a1.8 1.8 0 0 0 1.65-1.1 1.8 1.8 0 0 0-.36-2l-.06-.06 2.12-2.12.06.06a1.8 1.8 0 0 0 2 .36 1.8 1.8 0 0 0 1.1-1.65V3.5h3v.09a1.8 1.8 0 0 0 1.1 1.65 1.8 1.8 0 0 0 2-.36l.06-.06 2.12 2.12-.06.06a1.8 1.8 0 0 0-.36 2 1.8 1.8 0 0 0 1.65 1.1H21v3h-.09A1.8 1.8 0 0 0 19.4 15Z"/></svg>'};
const defaults={onboarded:false,points:1240,recycled:18.6,co2:4.2,pickups:[],reports:[],rewards:[],actions:[]};
let state={...defaults,...JSON.parse(localStorage.getItem('ecoloop-demo')||'{}')},page='home';
const content=document.querySelector('#content'),title=document.querySelector('#page-title'),modal=document.querySelector('#modal-root'),icon=n=>icons[n]||'';
const save=()=>localStorage.setItem('ecoloop-demo',JSON.stringify(state));
async function api(path, options = {}) {
  const response = await fetch(`/api${path}`, { headers: { 'Content-Type': 'application/json' }, ...options });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.message || 'Unable to save your update.');
  return payload;
}
async function refreshFromApi() {
  try {
    const data = await api('/dashboard');
    state = {
      ...state,
      points: data.impact.points,
      recycled: data.impact.recycledKg,
      co2: data.impact.co2Kg,
      pickups: data.pickups,
      reports: data.grievances,
      rewards: data.redemptions,
      actions: data.activity.map(item => ({ action: item.label, at: new Date(item.createdAt).toLocaleDateString() }))
    };
    save();
    render();
  } catch { /* Running index.html directly remains supported with local demo state. */ }
}
const quick=(a,l,k='')=>`<button class="quick-action" data-action="${a}"><span class="quick-icon ${k}">${icon(a==='report'?'alert':a==='scan'?'scan':a==='schedule'?'calendar':'gift')}</span>${l}</button>`;
const special=()=>state.pickups[0]?`<div class="bin-card"><span class="bin-symbol">${icon('calendar')}</span><div><strong>${state.pickups[0].type} pickup</strong><p>${state.pickups[0].slot} · ${state.pickups[0].id}</p><span class="status">CONFIRMED</span></div></div>`:'';
function home(){const report=state.reports[0]?`<div class="section-head"><h3>Your latest report</h3></div><div class="bin-card"><span class="bin-symbol">${icon('alert')}</span><div><strong>${state.reports[0].category}</strong><p>${state.reports[0].id} · Ward 12 team assigned</p><span class="status">OPEN</span></div></div>`:'';return `<div class="impact-card"><p class="impact-title">Your eco impact</p><div class="points">${state.points.toLocaleString()} <small>points</small></div><div class="impact-stats"><div><b>${state.recycled.toFixed(1)} kg</b>recycled</div><div><b>${state.co2.toFixed(1)} kg</b>CO₂ saved</div><div><b>#12</b>in your ward</div></div></div><div class="section-head"><h3>What would you like to do?</h3></div><div class="quick-grid">${quick('scan','Scan item')}${quick('schedule','Schedule','blue')}${quick('report','Report','orange')}${quick('rewards','Rewards','yellow')}</div><div class="section-head"><h3>Coming up</h3><button class="text-button" data-page="schedule">View calendar</button></div><button class="schedule-card" data-page="schedule"><span class="date-chip">OCT<b>05</b></span><span><strong>Dry waste collection</strong><small>Sunday · 8:00 – 10:00 AM</small></span><span class="card-arrow">${icon('chevron')}</span></button>${special()}${report}<div class="section-head"><h3>Bins near you</h3><button class="text-button" data-action="bins">Open map</button></div><div class="mini-map"><span class="road one"></span><span class="road two"></span><span class="pin p1">${icon('box')}</span><span class="pin p2">${icon('box')}</span><span class="pin p3">${icon('box')}</span><p class="map-caption">3 bins within 500 m</p></div>`}
function schedule(){const items=state.pickups.length?state.pickups.map(x=>`<div class="bin-card"><span class="bin-symbol">${icon('calendar')}</span><div><strong>${x.type}</strong><p>${x.slot} · ${x.id}</p><span class="status">CONFIRMED</span></div></div>`).join(''):'<p class="empty-copy">No special pickups scheduled yet.</p>';return `<div class="page-intro"><h3>Collection schedule</h3><p>Your collection days are set for Green Park, Ward 12.</p></div><div class="calendar-strip">${[['Sat','03'],['Sun','04'],['Mon','05'],['Tue','06'],['Wed','07'],['Thu','08'],['Fri','09']].map((d,i)=>`<span class="day ${i===2?'active':''}">${d}<b>${d[1]}</b></span>`).join('')}</div><div class="pickup-detail schedule-card"><span class="date-chip">OCT<b>05</b></span><div><span class="tag">UP NEXT</span><h4>Dry waste collection</h4><p>8:00 – 10:00 AM · Regular route</p><div class="timeline"><span class="done"></span><span></span><span></span></div></div></div><button class="primary-btn" data-action="pickup">Request a special pickup</button><div class="section-head"><h3>Requested pickups</h3></div>${items}`}
function rewards(){const rewards=state.rewards.length?`<div class="section-head"><h3>Your reward codes</h3></div>${state.rewards.map(x=>`<div class="bin-card"><span class="bin-symbol">${icon('gift')}</span><div><strong>${x.name}</strong><p>Show code <b>${x.code}</b> at checkout</p><span class="status">READY TO USE</span></div></div>`).join('')}`:'';let offers=[['☕','Free coffee',200,'coffee'],['🌱','Plant a tree',300,''],['🛒','₹50 grocery credit',500,'coffee'],['🎟️','Local store offer',350,'']];return `<div class="page-intro"><h3>Rewards that do good</h3><p>Turn mindful choices into small joys.</p></div><div class="reward-balance"><p>YOUR ECO POINTS</p><strong>${state.points.toLocaleString()}</strong><small>${Math.max(0,2000-state.points)} points to your next tier, Gold</small><div class="progress-track"><i style="width:${Math.min(100,state.points/20)}%"></i></div></div><div class="section-head"><h3>For you</h3><button class="text-button" data-action="history">History</button></div><div class="reward-grid">${offers.map(r=>`<article class="reward-card"><div class="reward-art ${r[3]}">${r[0]}</div><h4>${r[1]}</h4><p>${r[2]} points</p><button class="text-button" data-reward="${r[1]}" data-cost="${r[2]}">Redeem</button></article>`).join('')}</div>${rewards}`}
function profile(){return `<div class="profile-card"><div class="large-avatar">AK</div><h3>Aarav Khanna</h3><p>Green Park, Ward 12 · <b>Silver member</b></p></div><div class="menu-list">${[['user','Personal details'],['map','Saved addresses'],['settings','Notifications'],['gift','Invite a neighbour']].map(x=>`<button class="menu-row" data-action="profile-item">${icon(x[0])}<span>${x[1]}</span><span>${icon('chevron')}</span></button>`).join('')}</div><button class="secondary-btn" data-action="reset">Reset demo data</button>`}
function render(){if(page==='scan'){openScan();return}content.innerHTML=({home,schedule,rewards,profile})[page]();title.textContent=page==='home'?'Good morning, Aarav':page[0].toUpperCase()+page.slice(1);document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.querySelectorAll('[data-icon]').forEach(x=>x.innerHTML=icon(x.dataset.icon))}
function open(html){modal.innerHTML=`<div class="modal-backdrop"><section class="modal">${html}</section></div>`}const close=()=>modal.innerHTML='';
function openScan(){open(`<button class="modal-close" data-close>×</button><h3>Scan an item</h3><p>Hold your item inside the frame. We’ll tell you exactly what to do with it.</p><div class="camera"><div>${icon('scan')}<small>Point your camera at an item</small></div></div><div class="capture"><button data-action="capture" aria-label="Capture photo"></button></div><button class="secondary-btn" data-action="capture">Choose from gallery</button>`)}
function scanResult(){open(`<button class="modal-close" data-close>×</button><h3>We found a match</h3><div class="result"><span class="tag">RECYCLABLE · 94% CONFIDENT</span><h4>PET plastic bottle</h4><p>Blue dry-waste bin</p></div><h4>Make it count</h4><ol class="steps"><li>Empty and rinse the bottle.</li><li>Remove the cap and flatten it.</li><li>Place it in your dry-waste bin.</li></ol><button class="primary-btn" data-action="disposed">I disposed it · earn 5 points</button><button class="text-button" data-action="bins">Find a nearby bin</button>`)}
function openPickup(){open(`<button class="modal-close" data-close>×</button><h3>Special pickup</h3><p>We’ll find the next available slot near you.</p><div class="choice-grid">${['Bulky items','E-waste','Garden waste','Extra dry waste'].map(x=>`<button class="choice" data-choice>${x}</button>`).join('')}</div><div class="fake-input">📍 Green Park, Ward 12</div><button class="primary-btn" data-action="confirm-pickup">Find a slot</button>`)}
function openReport(){open(`<button class="modal-close" data-close>×</button><h3>Report an issue</h3><p>Your report helps keep the neighbourhood cleaner.</p><div class="choice-grid">${['Missed pickup','Overflowing bin','Littering','Other issue'].map(x=>`<button class="choice" data-choice>${x}</button>`).join('')}</div><textarea id="report-note" placeholder="Tell us what happened (optional)"></textarea><div class="fake-input">📍 Location: Green Park, Ward 12</div><button class="primary-btn" data-action="submit-report">Submit report</button>`)}
function bins(){open(`<button class="modal-close" data-close>×</button><h3>Nearby bins</h3><p>Choose a bin to get directions.</p><div class="bin-card"><span class="bin-symbol">${icon('box')}</span><div><strong>GP-041 · Dry waste</strong><p>230 m away · Park entrance</p><span class="status">42% FULL</span></div></div><div class="bin-card"><span class="bin-symbol">${icon('box')}</span><div><strong>GP-038 · Mixed recycling</strong><p>410 m away · Market road</p><span class="status">68% FULL</span></div></div><button class="primary-btn" data-action="directions">Get directions</button>`)}
function toast(m){let e=document.querySelector('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2800)}function record(action){state.actions.unshift({action,at:new Date().toLocaleDateString()});save()}
function onboarding(){open(`<div class="onboarding"><span class="welcome-leaf">↻</span><p class="eyebrow">WELCOME TO ECOLOOP</p><h3>Every small choice comes full circle.</h3><p>Scan items, keep up with collections, and earn rewards for caring for your neighbourhood.</p><button class="primary-btn" data-action="start">Get started</button><button class="text-button" data-action="start">I’ll explore first</button></div>`)}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.close)return close();if(b.dataset.page){page=b.dataset.page;return render()}if(b.dataset.choice){b.parentElement.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected'));return b.classList.add('selected')}let a=b.dataset.action;if(a==='scan')openScan();if(a==='schedule'){page='schedule';render()}if(a==='rewards'){page='rewards';render()}if(a==='report')openReport();if(a==='bins')bins();if(a==='capture')scanResult();if(a==='disposed'){state.points+=5;state.recycled+=.03;state.co2+=.01;record('Recycled PET bottle');close();page='home';render();toast('Nice work — 5 points added to your balance.')}if(a==='pickup')openPickup();if(a==='confirm-pickup'){let x=document.querySelector('.choice.selected');if(!x)return toast('Choose the type of waste first.');let p={type:x.textContent,id:`PK-${String(Date.now()).slice(-5)}`,slot:'Tomorrow · 4:00 – 6:00 PM'};state.pickups.unshift(p);record(`Requested ${p.type} pickup`);close();page='schedule';render();toast('Pickup confirmed for tomorrow, 4–6 PM.')}if(a==='submit-report'){let x=document.querySelector('.choice.selected');if(!x)return toast('Choose an issue category first.');let r={category:x.textContent,id:`GRV-${String(Date.now()).slice(-5)}`};state.reports.unshift(r);record(`Reported ${r.category}`);close();page='home';render();toast(`Report submitted. Ticket ${r.id} is being assigned.`)}if(a==='directions'){close();toast('Opening directions to GP-041…')}if(a==='profile-item')toast('This setting is ready for account integration.');if(a==='history')open(`<button class="modal-close" data-close>×</button><h3>Activity history</h3><p>Your recent EcoLoop actions.</p>${state.actions.length?state.actions.map(x=>`<div class="bin-card"><span class="bin-symbol">${icon('gift')}</span><div><strong>${x.action}</strong><p>${x.at}</p></div></div>`).join(''):'<p class="empty-copy">Your completed actions will show up here.</p>'}`);if(a==='start'){state.onboarded=true;save();close();toast('You’re ready to close the loop.')}if(a==='reset'){localStorage.removeItem('ecoloop-demo');state={...defaults,onboarded:true};page='home';render();toast('Demo data reset.')}if(b.dataset.reward){let c=Number(b.dataset.cost);if(state.points<c)return toast(`You need ${c-state.points} more points for this reward.`);state.points-=c;state.rewards.unshift({name:b.dataset.reward,code:`ECO-${Math.random().toString(36).slice(2,7).toUpperCase()}`});record(`Redeemed ${b.dataset.reward}`);page='rewards';render();toast(`${b.dataset.reward} reserved. Your code is ready.`)}});
document.addEventListener('click', e => {
  const button = e.target.closest('button');
  if (!button) return;
  const action = button.dataset.action;
  const request = async (path, options) => {
    try { await api(path, options); await refreshFromApi(); }
    catch (error) { toast(error.message); }
  };
  if (action === 'disposed') request('/scans', { method: 'POST' });
  if (action === 'confirm-pickup' && !button.isConnected && state.pickups[0]) request('/pickups', { method: 'POST', body: JSON.stringify({ type: state.pickups[0].type, slot: state.pickups[0].slot }) });
  if (action === 'submit-report' && !button.isConnected && state.reports[0]) request('/grievances', { method: 'POST', body: JSON.stringify({ category: state.reports[0].category }) });
  if (button.dataset.reward) request('/rewards/redeem', { method: 'POST', body: JSON.stringify({ name: button.dataset.reward, cost: Number(button.dataset.cost) }) });
  if (action === 'reset') request('/reset', { method: 'POST' });
});
document.querySelectorAll('[data-icon]').forEach(x=>x.innerHTML=icon(x.dataset.icon));render();if(!state.onboarded)onboarding();refreshFromApi();
